modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Bareback%20Horse%20Riding"
logoFile="icon.png"

[[mods]]
modId="barebackhorseriding"
version="2.0"
displayName="Bareback Horse Riding"
displayURL="https://serilum.com/mod/bareback-horse-riding"
authors="Rick South"
description='''Allows riding horses without a saddle, while wearing leather pants, to prevent slowness and/or damage.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Jack, Kreezxil, Michael W. S., Mir3JonCZ, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.barebackhorseriding]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.barebackhorseriding]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "barebackhorseriding.mixins.json"